# Setup
# title:               
# tagline:             'Brandon Smith'
# description:         ''
# url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Brandon Smith
  url:               tmp@gmail.com
  email:             tmp@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Pagination settings
paginate: 5  # Number of posts per page
paginate_path: "/blog/page:num/"  # URL structure for paginated pages
